export const US_STATES = [
  { value: 'AL', label: 'Alabama' },
  { value: 'AK', label: 'Alaska' },
  { value: 'AZ', label: 'Arizona' },
  { value: 'AR', label: 'Arkansas' },
  { value: 'CA', label: 'California' },
  { value: 'CO', label: 'Colorado' },
  { value: 'CT', label: 'Connecticut' },
  { value: 'DE', label: 'Delaware' },
  { value: 'FL', label: 'Florida' },
  { value: 'GA', label: 'Georgia' },
  { value: 'HI', label: 'Hawaii' },
  { value: 'ID', label: 'Idaho' },
  { value: 'IL', label: 'Illinois' },
  { value: 'IN', label: 'Indiana' },
  { value: 'IA', label: 'Iowa' },
  { value: 'KS', label: 'Kansas' },
  { value: 'KY', label: 'Kentucky' },
  { value: 'LA', label: 'Louisiana' },
  { value: 'ME', label: 'Maine' },
  { value: 'MD', label: 'Maryland' },
  { value: 'MA', label: 'Massachusetts' },
  { value: 'MI', label: 'Michigan' },
  { value: 'MN', label: 'Minnesota' },
  { value: 'MS', label: 'Mississippi' },
  { value: 'MO', label: 'Missouri' },
  { value: 'MT', label: 'Montana' },
  { value: 'NE', label: 'Nebraska' },
  { value: 'NV', label: 'Nevada' },
  { value: 'NH', label: 'New Hampshire' },
  { value: 'NJ', label: 'New Jersey' },
  { value: 'NM', label: 'New Mexico' },
  { value: 'NY', label: 'New York' },
  { value: 'NC', label: 'North Carolina' },
  { value: 'ND', label: 'North Dakota' },
  { value: 'OH', label: 'Ohio' },
  { value: 'OK', label: 'Oklahoma' },
  { value: 'OR', label: 'Oregon' },
  { value: 'PA', label: 'Pennsylvania' },
  { value: 'RI', label: 'Rhode Island' },
  { value: 'SC', label: 'South Carolina' },
  { value: 'SD', label: 'South Dakota' },
  { value: 'TN', label: 'Tennessee' },
  { value: 'TX', label: 'Texas' },
  { value: 'UT', label: 'Utah' },
  { value: 'VT', label: 'Vermont' },
  { value: 'VA', label: 'Virginia' },
  { value: 'WA', label: 'Washington' },
  { value: 'WV', label: 'West Virginia' },
  { value: 'WI', label: 'Wisconsin' },
  { value: 'WY', label: 'Wyoming' },
];

export const BUSINESS_INDUSTRIES = [
  { value: 'accounting-tax-services', label: 'Accounting & Tax Services' },
  { value: 'advertising-marketing', label: 'Advertising & Marketing' },
  { value: 'automotive', label: 'Automotive' },
  { value: 'beauty-health-fitness', label: 'Beauty, Health & Fitness' },
  { value: 'business-services', label: 'Business Services' },
  { value: 'childcare-education', label: 'Childcare & Education' },
  { value: 'cleaning-maintenance', label: 'Cleaning & Maintenance' },
  { value: 'construction', label: 'Construction' },
  { value: 'distribution', label: 'Distribution' },
  { value: 'dry-cleaners-laundromats', label: 'Dry Cleaners & Laundromats' },
  { value: 'food-beverage', label: 'Food & Beverage' },
  { value: 'franchises', label: 'Franchises' },
  { value: 'gas-stations-c-stores', label: 'Gas Stations & C-Stores' },
  { value: 'healthcare-medical', label: 'Healthcare & Medical' },
  { value: 'hotels-hospitality', label: 'Hotels & Hospitality' },
  { value: 'internet-technology', label: 'Internet & Technology' },
  { value: 'liquor-stores', label: 'Liquor Stores' },
  { value: 'manufacturing', label: 'Manufacturing' },
  { value: 'printing-publishing', label: 'Printing & Publishing' },
  { value: 'real-estate', label: 'Real Estate' },
  { value: 'restaurants', label: 'Restaurants' },
  { value: 'retail', label: 'Retail' },
  { value: 'transportation', label: 'Transportation' },
  { value: 'travel-recreation', label: 'Travel & Recreation' },
  { value: 'wholesale', label: 'Wholesale' },
];

export const PRICE_RANGES = [
  { value: 'under-50k', label: 'Under $50K', min: 0, max: 50000 },
  { value: '50k-100k', label: '$50K - $100K', min: 50000, max: 100000 },
  { value: '100k-250k', label: '$100K - $250K', min: 100000, max: 250000 },
  { value: '250k-500k', label: '$250K - $500K', min: 250000, max: 500000 },
  { value: '500k-1m', label: '$500K - $1M', min: 500000, max: 1000000 },
  { value: '1m-2m', label: '$1M - $2M', min: 1000000, max: 2000000 },
  { value: '2m-5m', label: '$2M - $5M', min: 2000000, max: 5000000 },
  { value: '5m-10m', label: '$5M - $10M', min: 5000000, max: 10000000 },
  { value: 'over-10m', label: 'Over $10M', min: 10000000, max: null },
];

export const REVENUE_RANGES = [
  { value: 'under-100k', label: 'Under $100K', min: 0, max: 100000 },
  { value: '100k-250k', label: '$100K - $250K', min: 100000, max: 250000 },
  { value: '250k-500k', label: '$250K - $500K', min: 250000, max: 500000 },
  { value: '500k-1m', label: '$500K - $1M', min: 500000, max: 1000000 },
  { value: '1m-2m', label: '$1M - $2M', min: 1000000, max: 2000000 },
  { value: '2m-5m', label: '$2M - $5M', min: 2000000, max: 5000000 },
  { value: '5m-10m', label: '$5M - $10M', min: 5000000, max: 10000000 },
  { value: 'over-10m', label: 'Over $10M', min: 10000000, max: null },
];

export const CASH_FLOW_RANGES = [
  { value: 'under-25k', label: 'Under $25K', min: 0, max: 25000 },
  { value: '25k-50k', label: '$25K - $50K', min: 25000, max: 50000 },
  { value: '50k-100k', label: '$50K - $100K', min: 50000, max: 100000 },
  { value: '100k-250k', label: '$100K - $250K', min: 100000, max: 250000 },
  { value: '250k-500k', label: '$250K - $500K', min: 250000, max: 500000 },
  { value: '500k-1m', label: '$500K - $1M', min: 500000, max: 1000000 },
  { value: 'over-1m', label: 'Over $1M', min: 1000000, max: null },
];

export const EMPLOYEE_RANGES = [
  { value: '1-5', label: '1-5 Employees', min: 1, max: 5 },
  { value: '6-10', label: '6-10 Employees', min: 6, max: 10 },
  { value: '11-25', label: '11-25 Employees', min: 11, max: 25 },
  { value: '26-50', label: '26-50 Employees', min: 26, max: 50 },
  { value: '51-100', label: '51-100 Employees', min: 51, max: 100 },
  { value: 'over-100', label: 'Over 100 Employees', min: 100, max: null },
];

export const ESTABLISHED_RANGES = [
  { value: '0-2', label: '0-2 Years', min: new Date().getFullYear() - 2, max: new Date().getFullYear() },
  { value: '3-5', label: '3-5 Years', min: new Date().getFullYear() - 5, max: new Date().getFullYear() - 3 },
  { value: '6-10', label: '6-10 Years', min: new Date().getFullYear() - 10, max: new Date().getFullYear() - 6 },
  { value: '11-20', label: '11-20 Years', min: new Date().getFullYear() - 20, max: new Date().getFullYear() - 11 },
  { value: 'over-20', label: 'Over 20 Years', min: 1900, max: new Date().getFullYear() - 21 },
];

export const LISTING_FEATURES = [
  { value: 'seller-financing', label: 'Seller Financing Available' },
  { value: 'management-stays', label: 'Management Will Stay' },
  { value: 'franchise', label: 'Franchise Opportunity' },
  { value: 'real-estate-included', label: 'Real Estate Included' },
  { value: 'absentee-owned', label: 'Absentee Owned' },
  { value: 'home-based', label: 'Home Based Business' },
  { value: 'semi-absentee', label: 'Semi-Absentee' },
  { value: 'relocation-provided', label: 'Relocation Provided' },
];

export const SORT_OPTIONS = [
  { value: 'newest', label: 'Newest Listed' },
  { value: 'oldest', label: 'Oldest Listed' },
  { value: 'price-low-high', label: 'Price: Low to High' },
  { value: 'price-high-low', label: 'Price: High to Low' },
  { value: 'revenue-high-low', label: 'Revenue: High to Low' },
  { value: 'cash-flow-high-low', label: 'Cash Flow: High to Low' },
];

export const MAJOR_METROPOLITAN_AREAS = [
  { value: 'new-york-ny', label: 'New York, NY', state: 'NY' },
  { value: 'los-angeles-ca', label: 'Los Angeles, CA', state: 'CA' },
  { value: 'chicago-il', label: 'Chicago, IL', state: 'IL' },
  { value: 'dallas-tx', label: 'Dallas, TX', state: 'TX' },
  { value: 'houston-tx', label: 'Houston, TX', state: 'TX' },
  { value: 'washington-dc', label: 'Washington, DC', state: 'DC' },
  { value: 'miami-fl', label: 'Miami, FL', state: 'FL' },
  { value: 'philadelphia-pa', label: 'Philadelphia, PA', state: 'PA' },
  { value: 'atlanta-ga', label: 'Atlanta, GA', state: 'GA' },
  { value: 'phoenix-az', label: 'Phoenix, AZ', state: 'AZ' },
  { value: 'boston-ma', label: 'Boston, MA', state: 'MA' },
  { value: 'san-francisco-ca', label: 'San Francisco, CA', state: 'CA' },
  { value: 'detroit-mi', label: 'Detroit, MI', state: 'MI' },
  { value: 'seattle-wa', label: 'Seattle, WA', state: 'WA' },
  { value: 'minneapolis-mn', label: 'Minneapolis, MN', state: 'MN' },
];